### ISSUE TITLE
why no make build ?

### ISSUE THREAD

**Issue by kerphi** [dailymotion/gazr#10]
there is a ``make run`` but why no build step ?

Example :
```makefile
build:
  docker build -t xxx/yyy .
```

**Comment by kerphi** [comment]
and thanks for your devoxx talk !

**Comment by tsunammis** [comment]
Hello @kerphi Sorry for the delay, I was preparing my holidays.

Yes, to be honest, we have the `build` task on a lot of internal projects. It would be a good thing to add it to the specification.

I'll be off during the next 3 weeks. Don't hesitate to contribute with a pull-request. I will take a look when I'll be back.

**Comment by tsunammis** [comment]
Hello @kerphi 

Sorry for the delay. I created a pull-request with your suggestion. -> https://github.com/dailymotion/gazr/pull/16

Have a nice day

**Comment by tsunammis** [comment]
the new task is now available on the website -> https://gazr.io/
