### ISSUE TITLE
feat: add (optional) "make init" command in spec

### ISSUE THREAD

**Issue by Djiit** [dailymotion/gazr#15]
Hi there,

Would you consider adding an "optional" `make init` command dedicated to pre-docker / non-docker stuff (e.g. importing a file/db dump from a remote s3, prompting user from some values...) ?

We just started to implement this on our side, but we would love to see it becoming part of the project if it makes any sense :).

Let me know if we can help

**Comment by tsunammis** [comment]
Hello @Djiit 

Glad to see you here.

The `init` task is interesting, we are already using it in some project. We didn't know if it would be useful to add it. You bring the response 👍 

@Djiit do you want to create the PR by yourself?

Best

**Comment by Djiit** [comment]
Sure i'll make a PR soon !

**Comment by tsunammis** [comment]
@Djiit  Great. I will add this details on the website after your PR will be merged.

**Comment by tsunammis** [comment]
The new task is now available on the website -> https://gazr.io/
