### ISSUE TITLE
dependency on make ?

### ISSUE THREAD

**Issue by tyrcho** [dailymotion/gazr#2]
I really like the idea behind this project ! (I attended Stan presentation in Worldline yesterday).

Seems to me that Windows developpers would also need to install some tool to support Makefiles ... any recommendation from your experience ?

**Comment by tsunammis** [comment]
You're right; Windows is not compliant by default without any tweak on its part.

In mind, I have 2 simple way:
* Use nmake 
* Use cygwin

We think to create a small binary which will be cross-platform, to avoid dependency on make which is not. Would you be interested?

**Comment by tyrcho** [comment]
What about a simple shell / batch file ? It would be simple enough so that maintaining a version for Linux/Mac and one for Windows should be OK.

**Comment by tyrcho** [comment]
After a good night sleep, I can see the point for make / the cross-platform binary. We'd like to have a portable format (like Makefile) to define the commands to run for `test`, `run` ...
A shell approach would have a lot of duplications between Windows batch format / Linux shell.

OTOH, I use [cmder](https://github.com/cmderdev/cmder) and I see most colleagues in Windows using it. It packages nicely a lot of shell tools. I just tested it with a simple shell file and it executes it just fine.

**Comment by tyrcho** [comment]
tested on Windows ... I don't have docker client installed but the commands are executed properly. Just run it with 

    sh gazr run

or

    sh gazr complexity


Which is quite close to the way I run it in Linux : 

    ./gazr complexity

**Comment by tsunammis** [comment]
Thank you for `Cmder`, I didn't know that project, it seems interesting. I will suggest it to our developers who are working on the Windows platform !

```
After a good night sleep, I can see the point for make / the cross-platform binary. We'd like to have a portable format (like Makefile) to define the commands to run for test, run ...
```
👍 In the past, we tried to use a common shell script, but it was a mess to maintain _(Compatibility between Sh, Bash, Zsh etc ...)_. Moreover, the extensibility, readability and the experience for the newcomers were really poor. Especially to add custom behavior to a specific task _(like `run`)_.

I don't remember if I already put the reasons of the Make _(Makefile)_ choice, here some of them:
* Readable / Alterable
* Understandable
* Available most of the time on each developers laptop*
* Flexible

*I know that the Windows platform doesn't support by default Make. Maybe we should provide some tutorial _(with Cmder for example)_. @tyrcho What do you think?

**Comment by tyrcho** [comment]
@tsunammis have you read my latest comments on this issue and had a look at https://github.com/tyrcho/gazr/blob/13ebface6d177825eafed956d3952df16cd578dc/examples/python/gazr ?

I have the feeling that all of the arguments for Make are also valid for this shell solution. And `sh` is easier to setup than Make (on Windows).

The Makefile I see also have some non trivial syntax, like 'PHONY'. I would argue that this `sh` syntax is 
- enough for what we need here
- even or better known than make amongst developpers in general
- more available than `make` (even on linux! I work in an [archlinux devbox](https://github.com/tyrcho/devbox) and I need to [install make](https://github.com/tyrcho/devbox/blob/master/scripts/install_std.sh)

I would howver restrict the shells to only `sh`.

----

In the end, is the choice between make and shell really in our hands ? I mean, there will be 2 groups of people concerned with gazr:
- those who provide scripts, dockerfile, services in xxx language
- those who run `gazr run` or similar.

I'm pretty sure some companies / open-source communities will prefer make, some will prefer shell, and some will come with a better (in their context) solution based on python/ruby/scala/whatever.

We are only offering examples here to help the 1st group of people.

Or did I miss something and we could provide more value than 'spec' and 'examples' ?

**Comment by tsunammis** [comment]
I agree with you, the problematics targeted by Gazr can be solved with a shell script.

As you said, some people prefer shell, other prefer Makefile. The choice is subjective, and after some debates, we decided to build the Gazr specification on top of Makefile.

One of the ideas we have to improve Gazr is to build a binary which manages the Makefile format and provide some features:
* Run tasks _(like Make does)_
* Check if the project respect the specification
* Help developers to create the tasks _(suggest library depending on the language used etc ...)_
* Provide binary for each platform _(Windows included)_

**Comment by tyrcho** [comment]
Understood :) thanks for the clarification !
