### ISSUE TITLE
Add common use-case: dependency vulnerability check

### ISSUE THREAD

**Issue by achedeuzot** [dailymotion/gazr#20]
I'd like to add a common use-case: external dependencies vulnerability checks.

As there is `security-sast`, I'd like to suggest adding `security-dependency-audit` or something in that spirit (I couldn't find a shorter name).
We could also add a top `security` makefile receipe that then calls `security-sast` and `security-dependency-audit`.

**Comment by tsunammis** [comment]
Hello @achedeuzot

What is being put behind the `security-dependency-audit` task?

Something which will list all the dependencies for a security audit?

have a nice day,

**Comment by achedeuzot** [comment]
The purpose is to scan all external dependencie (scanning `requirements.txt` with `safety` or `package.json` with `snyk` for known CVEs) during a CI build to prevent using vulnerable packages.

**Comment by tsunammis** [comment]
I'm wondering if we should name the task `security-dependency-check` or `security-dependency-audit`. OWASP describes it as "dependency check" -> https://www.owasp.org/index.php/OWASP_Dependency_Check

**Comment by achedeuzot** [comment]
Half of the tasks in Gazr are checks: formatting/style checking, test checking, complexity checking. Adding the `check` term doesn't add much information to the task IMHO. We could simply use `security-dependencies` ?

**Comment by tsunammis** [comment]
Thus, I noticed that **Gitlab** named it **Dependency scanning** -> https://docs.gitlab.com/ee/user/project/merge_requests/dependency_scanning.html

I would rather use `security-dependency-scan`, is it ok for you @achedeuzot ?

**Comment by achedeuzot** [comment]
Perfect ! 👍

**Comment by tsunammis** [comment]
@achedeuzot do you want to do the PR by yourself?

**Comment by tsunammis** [comment]
@achedeuzot is it ok for you?

**Comment by achedeuzot** [comment]
Yep :)

**Comment by tsunammis** [comment]
Great !
