### ISSUE TITLE
examples with corporate proxy

### ISSUE THREAD

**Issue by tyrcho** [dailymotion/gazr#8]
I struggled (and did not succeed to date) to make a working sample for a project which requires internet access to run the tasks, when executed behind my company's proxy.

This issue occurs for java / JVM projects (maven / gradle / sbt ... download depdencies from internet during build phase), and I guess it would also be an issue for ruby, javascript projects. Basically any stack which declares and download dependencies.

It is quite tricky to have docker images which work both behind an http proxy and without one. I think [transparent proxy](https://github.com/jpetazzo/squid-in-a-can) is a possibility but needs to be investigated further.

**Comment by tyrcho** [comment]
transparent proxy did not help for maven since it only uses the proxy if defined in `settings.xml`

I tried to suggest a solution which works both with and without a proxy

**Comment by tsunammis** [comment]
@tyrcho You're right, manage a proxy during a development / CI process is a little bit difficult. Especially when you use multiple services _(like SaaS one)_.

I don't have any ideas right now. I think it depends on your internal networking rules.
